version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /templates
  static_dir: templates
  secure: always

- url: /json
  static_dir: json
  secure: always

- url: /$
  static_files: index.html
  upload: index.html
  secure: always

- url: /.*
  script: wsgi_app.app
  secure: always


libraries:
- name: webapp2
  version: 2.5.2
